import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import './globals.css'
import ReactQueryProvider from './react-query-provider'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

export const metadata: Metadata = {
  title: 'k-tasts',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ReactQueryProvider>
            <ReactQueryDevtools initialIsOpen={false} />
            {children}
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
